language: node_js
sudo: false
node_js:
  - '8'

cache:
  yarn: true

branches:
  except:
    - "/^g3_.*$/"

env:
  matrix:
    - JOB=ci-checks
    - JOB=unit-core BROWSER_PROVIDER=browserstack
    - JOB=unit-jquery BROWSER_PROVIDER=browserstack
    - JOB=unit-modules BROWSER_PROVIDER=browserstack
    - JOB=docs-app BROWSER_PROVIDER=browserstack
    - JOB=e2e TEST_TARGET=jqlite BROWSER_PROVIDER=browserstack
    - JOB=e2e TEST_TARGET=jquery BROWSER_PROVIDER=browserstack
  global:
    - LOGS_DIR=/tmp/angular-build/logs
    - BROWSER_PROVIDER_READY_FILE=/tmp/browsersprovider-tunnel-ready
    - secure: "ikwydCnqDkZlGTfGHFckX8hCQzNoCVj5ca3yCqXbBgFlQh6QzEgCy9NsicA4FHNVPo3VSvyTymi00ZfiMSeracfXM8RnjjH9ybPZZ3rOiQXqVGwdKINQOj5Ba5y89iis2RwsUsjf6gB8HcXg6NynZgC6h0ESq5hfSVn4ubgrBHo="
    - secure: "VNPmToMrfPJyDFZqST/CwgknCtKWLcx5qGpJ8fmVgU+z1SpH2Fn2P4tMLzzs9vFw8n74JLv00Sdz1dC4W7/GeetmUjANbNxT0S7f55egDloiPFB1k6QA/TjYJft9GbvzBaiKOE3kmZBXDsvF4Vr6EGD1zKMiZY/NMh3HoLisiHw="

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - du -sh ./node_modules || true
  - "./scripts/travis/before_build.sh"
script:
  - "./scripts/travis/build.sh"

after_script:
  - "./scripts/travis/tear_down_browser_provider.sh"
  - "./scripts/travis/print_logs.sh"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d2120f3f2bb39a4531b2
      - http://104.197.9.155:8484/hubot/travis/activity #hubot-server
    on_success: always # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: always # default: false
